### ISSUE TITLE
Application killed on "Compute activity fingerprints"

### ISSUE THREAD

**Issue by klofrau** [martin-ueding/geo-activity-playground#100]
Application is killed when all memory is consumed, possibly due to a high value of variable "dim".
In my case: `[ 24556.44921875 167002.397436  ]`

https://github.com/martin-ueding/geo-activity-playground/blob/11fb381161dee7e9d04af018f2966c262a40ff09/geo_activity_playground/core/similarity.py#L77

Maybe due to corrupted gps data? Activity looks fine on Strava, but time_series shows distance of more than 30000 km

**Comment by martin-ueding** [comment]
That sounds like some bogus point of (0.0, 0.0) in your activity data. I'll just skip the fingerprint computation for these now. Perhaps once the activity loads, you will see that it has a point at the north pole or something.

**Comment by martin-ueding** [comment]
Version 0.20.0 is released you can update and try it out. If the issue persists, please reopen this ticket.
