### ISSUE TITLE
Support routes without time information

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#110]
User `@zwangseinweisung@mastodon.social` has GPX activity files which are routes and not tracks.

**Comment by ragnar76** [comment]
I'm here. For diagonisis, a file with a lot of tracks of routes is here: https://chaosadmins.de/gpx_tracks.tar.xz

**Comment by ragnar76** [comment]
Meanwhile, i was having a look at the files. Some files, like 27.05.2017_4_39_56_nachm.gpx are empty and have no tracks or routes inside. I will sort them out and try again

**Comment by ragnar76** [comment]
Okay, i was able to sort the faulty files and and "inject" some timestamps into them using GPS Utility (https://www.gpsu.co.uk/download.html). But still, it would be nice to have support for files without time informations

**Comment by martin-ueding** [comment]
I've managed to do it. Pandas has a nice concept of "not a time" which is a fancy "None" but for time information. This way you can now add GPX tracks without any time information. The one drawback is that it cannot be determined when the start date of that activity is. Therefore it doesn't show up in the list of recent activities and also doesn't show up in any of the summary statistics. But it is considered in the heatmap and the explorer tiles.

Will come out soon with version 0.23.0.
