### ISSUE TITLE
total km in daily view

### ISSUE THREAD

**Issue by ragnar76** [martin-ueding/geo-activity-playground#114]
It would be nice to sse the total km in daily view like in the image below. 

![grafik](https://github.com/martin-ueding/geo-activity-playground/assets/1709576/36f6c758-1b58-4c35-bcd3-520c48403d98)

**Comment by martin-ueding** [comment]
That's a good idea! This will be part of 0.24.0.

![Bildschirmfoto_20240623_113314](https://github.com/martin-ueding/geo-activity-playground/assets/976924/30cf7ab7-c0ad-4470-9e8f-877bafde4941)
