### ISSUE TITLE
Better summary statistics

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#115]
Think of some more interesting summary statistics.

**Comment by biker793** [comment]
Maybe add a plot with the cumulative distance per year. And some descriptive statistics such as mean distance per activity, mean speed, etc. Also some insights into the elevation gain would be interesting.

**Comment by martin-ueding** [comment]
Cumulative distance per year, you mean like so?

![image](https://github.com/martin-ueding/geo-activity-playground/assets/976924/7aae53f1-09ec-4814-ab06-c3637bfdbfdf)

**Comment by martin-ueding** [comment]
And mean values like this? Grouped by year and activity kind?

|   year |      Lauf |   Radfahrt |   Spaziergang |   Wanderung |
|-------:|----------:|-----------:|--------------:|------------:|
|   2013 | nan       |   14.3996  |       4.25801 |   nan       |
|   2014 | nan       |   13.2019  |       5.84334 |   nan       |
|   2015 | nan       |   21.7965  |       1.84459 |   nan       |
|   2016 | nan       |   41.783   |     nan       |   nan       |
|   2017 | nan       |   31.1637  |      12.3941  |    11.0778  |
|   2018 | nan       |   33.7149  |       4.41391 |    13.5971  |
|   2019 |   4.24556 |   17.1765  |       6.70514 |    19.6315  |
|   2020 | nan       |   17.6537  |       4.47838 |    14.0995  |
|   2021 |   6.4082  |   12.0258  |       2.76645 |    14.2149  |
|   2022 |   5.43118 |   14.4065  |       1.82764 |    16.4981  |
|   2023 | nan       |    9.32476 |       1.86585 |     6.58754 |
|   2024 | nan       |   10.2605  |       1.73369 |     6.22404 |

**Comment by martin-ueding** [comment]
Summary of each year:

![image](https://github.com/martin-ueding/geo-activity-playground/assets/976924/3ffea1cf-d87e-4498-bacd-c63614c5fed0)

Past 52 weeks:

![image](https://github.com/martin-ueding/geo-activity-playground/assets/976924/897e1790-a119-4509-b607-e96a716761f5)
