### ISSUE TITLE
Sharepic not found

### ISSUE THREAD

**Issue by ragnar76** [martin-ueding/geo-activity-playground#121]
Since a while, there are not sharepics and i think it is not intended ;) 

This is what i see in the logs
`2024-07-09 13:11:10 werkzeug INFO 172.17.0.1 - - [09/Jul/2024 13:11:10] "GET /activity/4049843474753545092/sharepic.png/sharepic.png HTTP/1.1" 404 -`

I run the docker image, rebuild the Image and clearing the cache does not help

**Comment by martin-ueding** [comment]
Sorry about that, I didn't adapt it properly to the new path system. Will be fixed in the next version.

**Comment by ragnar76** [comment]
You've done it. Thank you :+1:

**Comment by martin-ueding** [comment]
Fixed in 0.24.0.
