### ISSUE TITLE
Problem beim Docker Image bauen

### ISSUE THREAD

**Issue by alexander-klump** [martin-ueding/geo-activity-playground#125]
Ich habe beim Docker Image Bauen auf Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-116-generic x86_64) folgendes Problem:

![grafik](https://github.com/user-attachments/assets/fcb81c87-a26c-4f60-8d29-f52553513a1e)

Zum bauen benutze ich folgende Befehle (der Commit-Hash ist der letzte Release Commit Hash)

```
sudo git clone git@github.com:martin-ueding/geo-activity-playground.git
git reset --hard b0274660604754a28bae6a2edc8d4f62433b4724
cd geo-activity-playground
sudo docker build -t geo-activity-playground .
```

**Comment by martin-ueding** [comment]
Mir ist nicht ganz klar, was der Fehler ist. Ich habe mal die erwähnte `poetry.lock` aktualisiert.

Warum hast du das `git reset --hard b0274660604754a28bae6a2edc8d4f62433b4724` da nach dem `git clone` aber vor dem `cd`? Hast du deine Git-Repos in einem Git-Repo?

Kannst du im Order `geo-activity-playground` nochmal `git pull` machen und erneut das `sudo docker build ...` ausprobieren?

**Comment by alexander-klump** [comment]
Das mit dem `git reset --hard b0274660604754a28bae6a2edc8d4f62433b4724` vor dem `cd` ist ein Fehler.

Nun bekomme ich keinen Fehler mehr. `git pull` habe ich nicht gemacht, aber ich  führe auf dem Server immer ein Skript mit folgendem Teilinhalt aus:

```
sudo rm -rf geo-activity-playground
sudo git clone git@github.com:martin-ueding/geo-activity-playground.git
cd geo-activity-playground
#git reset --hard b0274660604754a28bae6a2edc8d4f62433b4725
sudo docker build -t geo-activity-playground .
```

**Comment by martin-ueding** [comment]
Gut, wenn du immer ein neues `git clone` machst, dann hast du die letzte Version.

Freut mich, dass es geklappt hat!
