### ISSUE TITLE
Nach Update bleiben Kind, Commute und Equipment ohne Zuordnung

### ISSUE THREAD

**Issue by markwaypoint** [martin-ueding/geo-activity-playground#130]
Nach einem erfolgreichen 'pip install -U geo-activity-playground' auf einer lokalen Windows installation, sind nach start des Servers keine Equipment, Kind und Commute zuordnungen in den Aktivitäten, in der vorherigen Version funktionierten die Zuordnungen des Kinds, des Commutes und des Equopments.
Ein löschen des Inhalts des Cache Ordners und ein neustart des Servers brachten keine Abhilfe.

**Comment by martin-ueding** [comment]
Kann es sein, dass du schon ziemlich lange nicht mehr aktualisiert hast? Ich habe inzwischen die Ordnerstruktur frei wählbar gemacht, siehe [die Dokumentation](https://martin-ueding.github.io/geo-activity-playground/getting-started/using-activity-files/#directory-structure). Wenn du das alte Muster erhalten willst, musst du das hier in die `config.toml` packen:

```toml
metadata_extraction_regexes = [
    '(?P<kind>[^/]+)/(?P<equipment>[^/]+)/(?P<name>[^/]+)/',
    '(?P<kind>[^/]+)/(?P<equipment>[^/]+)/[-\d_ ]+(?P<name>[^/]+)(?:\.\w+)+$',
    '(?P<kind>[^/]+)/[-\d_ ]+(?P<name>[^/]+)(?:\.\w+)+$',
]
```

**Comment by markwaypoint** [comment]
Das wird so sein. Probiere ich aus. Am 03.08.2024 um 16:46 schrieb Martin Ueding ***@***.***>:﻿
Kann es sein, dass du schon ziemlich lange nicht mehr aktualisiert hast? Ich habe inzwischen die Ordnerstruktur frei wählbar gemacht, siehe die Dokumentation. Wenn du das alte Muster erhalten willst, musst du das hier in die config.toml packen:
metadata_extraction_regexes = [
    '(?P<kind>[^/]+)/(?P<equipment>[^/]+)/(?P<name>[^/]+)/',
    '(?P<kind>[^/]+)/(?P<equipment>[^/]+)/[-\d_ ]+(?P<name>[^/]+)(?:\.\w+)+$',
    '(?P<kind>[^/]+)/[-\d_ ]+(?P<name>[^/]+)(?:\.\w+)+$',
]

**Comment by markwaypoint** [comment]
Hm, also:
Da ich noch keine config.toml hatte, habe ich eine Textdatei erstellt, das snippet da hinein kopiert, die Datei zu config.toml umbenannt. Sie liegt jetzt zusammen mit der start.bat im gleichen Verzeichnis. Danach habe ich den inhalt des Cache Ordners gelöscht und start.bat ausgeführt. Ich habe weiter keine Equipment Zuordnung, meine aber, dass der Fehler irgendwo bei mir liegt.

**Comment by martin-ueding** [comment]
Hast du dann diese Struktur hier?

![image](https://github.com/user-attachments/assets/155578b8-bbd4-4791-bf6d-236fd56888f6)

**Comment by martin-ueding** [comment]
Besteht hier noch Interesse?
