### ISSUE TITLE
Import from Strava Export fails because of changed csv format

### ISSUE THREAD

**Issue by p3dda** [martin-ueding/geo-activity-playground#131]
Importing a Strava export throws the error, because of unexpected number of columns in the CSV file:

> Your file has 94 but we expect 87. This means that the program needs to be updated to match the new Strava export format

`Index(['Aktivitäts-ID', 'Aktivitätsdatum', 'Name der Aktivität',
       'Aktivitätsart', 'Aktivitätsbeschreibung', 'Verstrichene Zeit',
       'Distanz', 'Max. Herzfrequenz', 'Relative Leistung', 'Pendeln',
       'Hinweis zur Privatsphäre für Aktivitäten', 'Aktivitätsausrüstung',
       'Dateiname', 'Sportlergewicht', 'Fahrradgewicht', 'Verstrichene Zeit.1',
       'Bewegungszeit', 'Distanz.1', 'Höchstgeschw.',
       'Durchschnittliche Geschwindigkeit', 'Höhenzunahme', 'Höhenunterschied',
       'Min. Höhe', 'Max. Höhe', 'Max. Steigung', 'Durchschnittliche Steigung',
       'Durchschnittliche positive Steigung',
       'Durchschnittliche negative Steigung', 'Max. Tritt-/Schrittfrequenz',
       'Durchschnittliche Trittfrequenz', 'Max. Herzfrequenz.1',
       'Durchschnittliche Herzfrequenz', 'Max. Watt', 'Durchschnittliche Watt',
       'Kalorien', 'Max. Temperatur', 'Durchschnittliche Temperatur',
       'Relative Leistung.1', 'Gesamtarbeit', 'Anzahl Läufe', 'Bergaufzeit',
       'Bergabzeit', 'Andere Zeit', 'Gefühlte Anstrengung', 'Art', 'Startzeit',
       'Gewichtete durchschnittliche Leistung', 'Leistungszahl',
       'Gefühlte Anstrengung verwenden', 'Gefühlte relative Leistung',
       'Pendeln.1', 'Insgesamt gestemmtes Gewicht', 'Von Upload',
       'Auf Steigung angepasste Distanz', 'Wetterbeobachtungszeit',
       'Wetterlage', 'Wetter: Temperatur', 'Scheinbare Temperatur', 'Taupunkt',
       'Luftfeuchtigkeit', 'Wetter: Druck', 'Windgeschwindigkeit', 'Windböe',
       'Windrichtung', 'Niederschlagsintensität', 'Sonnenaufgangszeit',
       'Sonnenuntergangszeit', 'Mondphase', 'Fahrrad', 'Ausrüstung',
       'Niederschlagswahrscheinlichkeit', 'Niederschlagsart', 'Wolkendecke',
       'Wetter: Sichtbarkeit', 'UV-Index', 'Wetter: Ozon', 'Sprunganzahl',
       'Schwierigkeit insgesamt', 'Durchschnittlicher Flow', 'Markiert',
       'Durchschnittsgeschwindigkeit im Aufzeichnungszeitraum',
       'Auf Schotter zurückgelegte Distanz', 'Neu getestete Distanz',
       'Neu getestete Schotterdistanz', 'Aktivitätsanzahl',
       'Schritte insgesamt', 'Eingesparte CO₂-Emissionen', 'Pool-Länge',
       'Trainingsbelastung', 'Intensität',
       'Durchschnittliches auf Steigung angepasstes Tempo', 'Stoppuhr-Zeit',
       'Zyklen gesamt', 'Medien'],
      dtype='object')`

**Comment by martin-ueding** [comment]
Thank you very much for the updated list!
