### ISSUE TITLE
Compressed activities cannot be imported from Strava Checkout

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#145]
When importing gpx files, if the activity is still in a `activityname.gpx.gz` there is an error `"Filename"`. Manually changing the `activities.csv` and removing the` .gz` from the filename works.

_Originally posted by @eifelkiwi in https://github.com/martin-ueding/geo-activity-playground/issues/112#issuecomment-2276159078_

**Comment by martin-ueding** [comment]
This is strange, I have a test case where the `Filename` is just `activities/12866632127.fit.gz`:

```csv
Activity ID,Activity Date,Activity Name,Activity Type,Activity Description,Elapsed Time,Distance,Max Heart Rate,Relative Effort,Commute,Activity Private Note,Activity Gear,Filename,Athlete Weight,Bike Weight,Elapsed Time,Moving Time,Distance,Max Speed,Average Speed,Elevation Gain,Elevation Loss,Elevation Low,Elevation High,Max Grade,Average Grade,Average Positive Grade,Average Negative Grade,Max Cadence,Average Cadence,Max Heart Rate,Average Heart Rate,Max Watts,Average Watts,Calories,Max Temperature,Average Temperature,Relative Effort,Total Work,Number of Runs,Uphill Time,Downhill Time,Other Time,Perceived Exertion,Type,Start Time,Weighted Average Power,Power Count,Prefer Perceived Exertion,Perceived Relative Effort,Commute,Total Weight Lifted,From Upload,Grade Adjusted Distance,Weather Observation Time,Weather Condition,Weather Temperature,Apparent Temperature,Dewpoint,Humidity,Weather Pressure,Wind Speed,Wind Gust,Wind Bearing,Precipitation Intensity,Sunrise Time,Sunset Time,Moon Phase,Bike,Gear,Precipitation Probability,Precipitation Type,Cloud Cover,Weather Visibility,UV Index,Weather Ozone,Jump Count,Total Grit,Average Flow,Flagged,Average Elapsed Speed,Dirt Distance,Newly Explored Distance,Newly Explored Dirt Distance,Activity Count,Total Steps,Carbon Saved,Pool Length,Training Load,Intensity,Average Grade Adjusted Pace,Timer Time,Total Cycles,Media
12070555079,"May 29, 2022, 3:53:35 PM",Laufen Landal Park,Run,"",1428,3.32,,,false,"",,activities/12866632127.fit.gz,,,1428.0,1411.0,3322.949951171875,3.2149860858917236,2.355031967163086,61.878849029541016,86.0,357.20001220703125,376.70001220703125,12.508076667785645,0.0,,,80.0,71.25904846191406,,,,,262.0,,,,,,,,,,,,,,,,0.0,,1.0,3473.800048828125,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,2.326995849609375,0.0,,,,3344.0,,,,,2.461941957473755,,,""
```

Also I don't understand how "removing `.gz` from the filename" makes it work; the file is still compressed. I would think that it couldn't be loaded then.

Can you perhaps elaborate a bit? What does the row in your CSV file look like? And does the referenced file exist?

**Comment by eifelkiwi** [comment]
I wasn't able to reproduce this, sorry.

But: I have to gpx.gz activities that give errors with "Latitude not found" although both contain GPS data. At least they look like regular gpx files to me. Extracting them prior to the import did not help the problem.

The CSV with metadata:
[activities-gpx-error.csv](https://github.com/user-attachments/files/16801969/activities-gpx-error.csv)

The gpx file:
[2668648455.zip](https://github.com/user-attachments/files/16801961/2668648455.zip)

The error message:
[2024-08-29_gpx-gz-import-error.txt](https://github.com/user-attachments/files/16801979/2024-08-29_gpx-gz-import-error.txt)

**Comment by martin-ueding** [comment]
I've looked into your file and I don't see what's wrong with it. But I cannot import it either.
