### ISSUE TITLE
Improvement: Harmonized graphics

### ISSUE THREAD

**Issue by eifelkiwi** [martin-ueding/geo-activity-playground#155]
On the Summary page, graphics showing similar data (e.g. weekly, monthly activities) should feature the same colour scheme (the same colour per type of activity).

Additionally maybe an option to toggle different colour styles apart from 'viridis'.

**Comment by martin-ueding** [comment]
I've added a settings menu for choosing a color scheme. All the kinds are now consistent with each other across plots. Comes in the next version.

![Bildschirmfoto_20240921_232405](https://github.com/user-attachments/assets/980cd002-6776-4e56-9284-b615b9e27154)
