### ISSUE TITLE
Sharepic für die Tagesansicht

### ISSUE THREAD

**Issue by ragnar76** [martin-ueding/geo-activity-playground#157]
Die einzelnen Aktivitäten haben ein Sharepic aber in der Tagesansicht fehlt dieses. Wäre cool da auch eins zu haben.

![grafik](https://github.com/user-attachments/assets/474718d7-73aa-47d7-b0f9-39ebab2f23aa)

**Comment by martin-ueding** [comment]
Sollen auf dem Sharepic die Aktivitäten des Tages in unterschiedlichen Farben sein, so wie auf der interaktiven Karte im Bildschirmfoto? Oder alles eine rote Linie? Sollen die Arten der Aktivitäten in Farben unterschieden werden (z.B. Triathlon, Autofahrt zum Wanderparkplatz)? Willst du im Sharepic eine Auflistung der Aktivitäten, eine Aggregation nach Art ("kind") oder nur eine Gesamtdistanz und -zeit?

**Comment by ragnar76** [comment]
Mir würde es reichen wenn die komplett in rot sind wie bei den anderen Bildern auch. Da ich keine anderen Aktivitäten als Radfahren aufnehme sind unterschieliche Farben zweitrangig.

**Comment by martin-ueding** [comment]
Ich habe da jetzt eine Version implementiert:

![grafik](https://github.com/user-attachments/assets/8473e030-90e6-4417-a462-952d8f9cfa71)

**Comment by martin-ueding** [comment]
Ist dann in Version 0.34.0 verfügbar.
