### ISSUE TITLE
Settings per Passwort schützen

### ISSUE THREAD

**Issue by ragnar76** [martin-ueding/geo-activity-playground#159]
Wie Du vielleicht weißt lasse ich meine Instanz öffentlich laufen (https://tracks.theragnarbay.org/). Da ist es ungünstig dass die Settings für jeden les bzw. schreibbar sind. Ließe sich das irgendwie per Passwort schützen oder ggf. über erlaubte IP-Adressen regeln?

**Comment by martin-ueding** [comment]
Klingt, als bräuchten wir langsam ein Zugriffsmanagement. Muss ich mal überlegen.

**Comment by martin-ueding** [comment]
Ging jetzt recht einfach: Man muss einmal das Passwort eingeben, dann wird das in der Session hinterlegt. Somit muss man das nicht ständig eingeben. Und man kann auch im Web-Interface das Passwort setzen und ändern. Aber nur, wenn es entweder kein Passwort gibt oder man schon eingeloggt ist. Das sollte jetzt soweit sicher sein, wenn ich keinen Denkfehler gemacht habe.

![Bildschirmfoto_20240907_133154](https://github.com/user-attachments/assets/a14fda99-136f-491c-87d6-a755ab6ace12)

![Bildschirmfoto_20240907_133201](https://github.com/user-attachments/assets/07d79259-f494-4209-beed-72dd03236e47)

![Bildschirmfoto_20240907_133504](https://github.com/user-attachments/assets/0199903d-b0b5-43b7-8dec-576558d85cae)

![Bildschirmfoto_20240907_133518](https://github.com/user-attachments/assets/8899c013-5da3-4f83-84fe-17b8fccfa029)

**Comment by ragnar76** [comment]
Probier ich heute abend aus wenn die Kinder im Bett sind

**Comment by ragnar76** [comment]
Löift :)

Aber ist es eine so gute Idee das Passwort ins Log zu schreiben? ;)

**Comment by martin-ueding** [comment]
Wunderbar, freut mich! Das war noch ein `print()` zum Entwickeln, ist in der nächsten Version dann raus.
