### ISSUE TITLE
Lücken im Track

### ISSUE THREAD

**Issue by ragnar76** [martin-ueding/geo-activity-playground#162]
Mir ist aufgefallen dass es immer mal wieder Lücken im Track gibt. Wohl anscheinend wenn ich irgendwo stehen bleibe. Muss das so und kann man das ggf. irgendwo abstellen? 
![grafik](https://github.com/user-attachments/assets/8277c11f-1529-4108-b0f0-7bf37362505c)

**Comment by martin-ueding** [comment]
Das ist leider so eine Grundsatzfrage. Früher gab es keine Lücken, da haben sich Leute darüber beschwert. Manche pausieren eine Aktivität und setzen sie dann an anderer Stelle fort. Da wollen sie dann keine gerade Linie zwischen den Punkten haben. Je nach App wird auch durchgehend aufgenommen, wenn man stehenbleibt.

Ich muss mal überlegen, ob man die Schwellen für Pausen konfigurierbar machen sollte. Das wird dann allerdings fies, weil man dann auch die Kacheln neu ableiten muss.

**Comment by ragnar76** [comment]
Meiner Meinung nach sieht das ganz schön bescheiden aus wenn da keine durchgehende Linie ist nur weil man ne Verabredung mit dem Busch hat :grin: , was trinkt, eine raucht oder einfach nur an einer roten Ampel steht.

**Comment by beautiful-orca** [comment]
![2024-10-04_01-16](https://github.com/user-attachments/assets/6f2240bf-50c1-4889-8bda-eab9aa3741e7)
Ich hab auch größere Lücken im Track bei geo-activity-playground. Da ist teilweise ein langer Tunnel, weshalb die aufgenommenen track points vielleicht keine gute Qualität haben.

Allerdings mag ich das lieber ohne Lücken wie z.B. in Organic Maps oder bikerouter.de
![2024-10-04_01-22](https://github.com/user-attachments/assets/b804b542-8f6b-4b83-b38b-a950e2bb8bd7)

**Comment by ragnar76** [comment]
Der Kommentar hier hat nichts mit dem Issue selber zu tun aber ich bin überrascht noch jemanden aus Duisburg (oder zumindest da lang gefahren) zu treffen. Schöne Grüße aus Hüttenheim! 😄

**Comment by martin-ueding** [comment]
In der nächsten Version kann man es einstellen. Standardwert ist, dass das deaktiviert ist.

![Bildschirmfoto_20241025_114351](https://github.com/user-attachments/assets/8fed07ef-6895-4060-b177-c62e4d6a8840)

![Bildschirmfoto_20241025_114400](https://github.com/user-attachments/assets/f372b87c-924f-4be5-98eb-8b1f7e55f08c).

**Comment by martin-ueding** [comment]
Ich habe den Standard doch bei den 30 Sekunden gelassen, die es vorher waren. Wenn man das ausstellen will, muss man dort explizit die 0 eintragen. Das hat dann den Vorteil, dass die Aktivitäten erneut verarbeitet werden. Somit kommt man nicht in die inkonsistente Situation, dass plötzlich neue Aktivitäten das nicht haben, die alten aber schon.
