### ISSUE TITLE
Explorer Tiles bzw. Squadratinhos in der Routenansicht

### ISSUE THREAD

**Issue by ragnar76** [martin-ueding/geo-activity-playground#166]
Ich bin jetzt nicht jemand der jedem Explorer Tile oder den Squadratinhos hinterher rennt aber wenn ich doch mal neue hab (so wie im Screenshot unten) würde ich doch ganz gerne wissen was neu ist. Wäre möglich das in die Routenansicht mit einzubauen. Ggf. wäre eine eigene Seite dafür Übersichtlicher.

![grafik](https://github.com/user-attachments/assets/ab968814-fe7a-4058-90b7-e43bf7cc6590)

**Comment by martin-ueding** [comment]
That's a nice idea! Will be in the next version.

![Bildschirmfoto_20240927_185305](https://github.com/user-attachments/assets/b6c13d39-129d-473f-9f18-90bdf6404013)

**Comment by ragnar76** [comment]
Wow! Das ging fix. Danke schön :smiley:
