### ISSUE TITLE
"Activities with the same name" sortierbar machen

### ISSUE THREAD

**Issue by ragnar76** [martin-ueding/geo-activity-playground#168]
Ich fänds praktisch wenn man "Date", "Distance / km", "Elapsed time" und "Equipment" sortierbar wäre (in SQL z.b. "order by distance asc/desc"). Dann könnte man schnell, in meinem Fall, nach Datum sortieren, schnell erkennen welche Strecke am längsten/kürzesten war, wie lange man unterwegs war usw.

![grafik](https://github.com/user-attachments/assets/ce51e3bc-ffce-4a66-b7f7-87e374991395)

**Comment by ragnar76** [comment]
Edit: Auch hier wäre das ggf. hilfreich "activity/name/gpx"

**Comment by martin-ueding** [comment]
Was meinst du mit "activity/name/gpx"?

**Comment by ragnar76** [comment]
DIe URL, also https:/foo.bar/activity/name/$NAME . "gpx" war der name bevor ich das regex aus #156 geändert habe.

**Comment by martin-ueding** [comment]
Ah, du meinst die URL. Dann verstehe ich das. Ja, das wäre generell bei allen derartigen Tabellen hilfreich.

**Comment by martin-ueding** [comment]
Gerade gesehen, dass das nicht korrekt numerisch gemacht wird. Ist jetzt besser:

![Bildschirmfoto_20241025_101027](https://github.com/user-attachments/assets/6c1ec005-dbdb-42d9-aa44-117b6f0c77e5)
