### ISSUE TITLE
Ignore activities in multiple formats

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#173]
Von @multiburst:

Da die Tracks doppelt als GPX/KML vorliegen, wäre eine Filterung für den Scan sinnvoll. Gern auch einfach nur als config/text Filter. Gibt glaub einige Tools, die nach Routenende mehrere Formate ausspucken - und das irritiert ja dann jegliche Statistik.

Textdatei oder Parameter mit den Formaten zum ein/ausschließen wäre dann der Wunsch. Oder einfach KML/Z ignorieren ;)

**Comment by martin-ueding** [comment]
Ich habe es jetzt hinzugefügt, aber ganz primitiv erstmal. In der `config.json` diese Zeile hinzufügen:

```json
"ignore_suffixes": [".kml", ".kmz"],
```

**Comment by multiburst** [comment]
Kurze Frage: hab grad geupdated auf die 0.41.0

Beim Start gab es Probleme mit einer KML Datei. Hab dann das Playground Verzeichnis nochmal geleert um neu anzufangen.

Die config.json wird nicht mehr erstellt und ist nicht dokumentiert, so weit ich sehe. Wie sollte die denn im Grundgerüst aussehen?

**Comment by martin-ueding** [comment]
Die `config.json` wird erst erstellt, wenn sie von den Standardwerten abweicht. Sobald du über die Web-Oberfläche Einstellungen vornimmst, wird die angelegt.

**Comment by martin-ueding** [comment]
Ach stimmt, du nutzt da ja die undokumentierte Option. Hier ist der Code dazu: https://github.com/martin-ueding/geo-activity-playground/blob/main/geo_activity_playground/core/config.py

Von daher sollte das wohl so aussehen:

```json
{
  "ignore_suffixes": [".kml"]
}
```
