### ISSUE TITLE
Tabelarische Übersicht über alle Tracks

### ISSUE THREAD

**Issue by ragnar76** [martin-ueding/geo-activity-playground#174]
Dein Kommentar in #168

> Ja, das wäre generell bei allen derartigen Tabellen hilfreich.

hat mich stutzig gemacht. Gibts egtl. eine tabelarische Übersicht aller Tracks? Ich glaube das wäre ganz nett.

**Comment by beautiful-orca** [comment]
Es gibt die Auflistung der Gesamtkilometer unter `/calendar` und die monatliche Auflistungen der Track Namen, `/calendar/2024/9`.

Eine gefilterte und sortierbare Tabelle wäre cool.

Die monatliche Ansicht könnte aber auch so schön wie die Startseite des WebUI aussehen (also die Tracks mit Karte, Name, Kind, Distanz, Zeit, Datum)

**Comment by martin-ueding** [comment]
Suchfunktion habe ich jetzt gebaut. Dann bekommt man eine Tabelle mit allem, was man gefunden hat. Wenn man nicht einschränkt, bekommt man alles.

![Bildschirmfoto_20241025_100616](https://github.com/user-attachments/assets/33819c41-688b-46a1-ab10-0f9f26d3a74c)
