### ISSUE TITLE
OsmAnd becomes very sluggish when viewing missing tiles from gpx export

### ISSUE THREAD

**Issue by beautiful-orca** [martin-ueding/geo-activity-playground#175]
This problem is mentioned in the [documentation](https://martin-ueding.github.io/geo-activity-playground/features/explorer-tiles/#missing-tiles-on-the-go) already, but no other FOSS solution for offline tile hunting is mentioned

I suggest to add [OrganicMaps](https://organicmaps.app/) which can display those missing tile exports (gpx) without issues on a offline map.

OrganicMaps can also record tracks, so it might be mentioned on other pages of the documentation too.

**Comment by beautiful-orca** [comment]
Track naming of exported gpx files is not good for Organic Maps tho. So i just use it to look up the missing tiles and record with OsmAnd.

**Comment by martin-ueding** [comment]
I now mention Organic Maps in the documentation.
