### ISSUE TITLE
Bump DOCKERFILE python version from 3.11 to 3.12

### ISSUE THREAD

**Issue by beautiful-orca** [martin-ueding/geo-activity-playground#184]
I think geo-activity-playground is ready to run on python 3.12.

I tested it with a build of DOCKERFILE with `python:3.12-slim` and did not encounter problems.
Issues with pydantic with python 3.12 have been resolved #160

**Comment by martin-ueding** [comment]
Good idea! The project is compatible with `python = "^3.10,<3.13"` at the moment, so I've updated the `Dockerfile` to 3.12.
