### ISSUE TITLE
Favicon is different from the updated logo

### ISSUE THREAD

**Issue by beautiful-orca** [martin-ueding/geo-activity-playground#187]
The logo has been [changed in V0.20](https://github.com/martin-ueding/geo-activity-playground/commit/4057834cfe3565aa5511589b009a4f1bd236e342) but the favicon.ico , android-chrome-384x384.png and safari-pinned-tab.svg have not been updated since the initial commit #19 

Is this intended or can we have the new logo as favicon too?

Relevant directory: [/geo_activity_playground/webui/static](https://github.com/martin-ueding/geo-activity-playground/tree/master/geo_activity_playground/webui/static)

**Comment by martin-ueding** [comment]
Ah, I forgot to use https://realfavicongenerator.net/ after the logo change. Fixed it for the next version.
