### ISSUE TITLE
Cleaning up kinds of activities coming from Strava

### ISSUE THREAD

**Issue by biker793** [martin-ueding/geo-activity-playground#188]
Hi,
somehow the language from my activities switch from German to English. And since the latest update of the playground I also get a 'root:' prefix. The latter might be fixed easily, but fixing the mix of German and English names is coming from my side. Maybe a group renaming function in the options would be feasible
![Screenshot 2024-10-17 at 20-40-18 Geo Activity Playground](https://github.com/user-attachments/assets/55176c07-f066-4354-bf02-01b637eda8ed)

**Comment by martin-ueding** [comment]
The `root` thing comes from stravalib 2.0; I've fixed that.

For the renaming I've implemented something for you:

![Bildschirmfoto_20241025_185341](https://github.com/user-attachments/assets/bd522f75-2a51-491f-8a11-13142bd9a00f)

![Bildschirmfoto_20241025_185349](https://github.com/user-attachments/assets/b548a6b1-fe18-491c-8ba1-149e797c23ea)

In your case you'd need to enter these rules:

```
Ride => Radfahrt
Run => Lauf
Walk => Spaziergang
root='Ride' => Radfahrt
root='Run' => Lauf
root='Walk' => Spaziergang
```

Then it should re-scan for activities and everything should be resolved.

Will be available in version 0.30.0 that I'll release later today. Please reopen if it isn't solved.
