### ISSUE TITLE
Heatmap incomplete in smaller zoom levels

### ISSUE THREAD

**Issue by biker793** [martin-ueding/geo-activity-playground#189]
The Heatmap shows only parts of my tracks when I'm on lower zoom levels. When I zoom in more tracks appear. Might be connected to #188 , since I enabled the renaming option. Also when I choose only single kinds of activities, the heatmap is not complete.

**Comment by martin-ueding** [comment]
Could you delete the directory `Playground/Cache/Heatmap` and restart the application?

If the problem persists, could you perhaps create some screenshots?

**Comment by biker793** [comment]
Yes that did the trick :)

**Comment by martin-ueding** [comment]
Then there is a problem with the cache invalidation for the heatmap. This shouldn't happen, the program should automatically detect when activities have had their kind changed.

**Comment by martin-ueding** [comment]
Now I've fixed the cache expiry. This way you can happily change the kinds of activities and it will automatically pick that up in the future.
