### ISSUE TITLE
Missing explorer maps since 0.33.0

### ISSUE THREAD

**Issue by PelikhanWebDev** [martin-ueding/geo-activity-playground#198]
After updating to the newest version, the maps for both zoom levels went missing...
(Using Geo Activity Playground on macOS 15.1)

<img width="1175" alt="Screenshot 2024-11-16 at 21 24 05" src="https://github.com/user-attachments/assets/45604005-d070-4469-b051-696fd10a9ae9">

**Comment by martin-ueding** [comment]
The problem was that VS Code auto-formatted the embedded JavaScript and created syntax errors. Fixed in 0.33.2.
