### ISSUE TITLE
Unbekannte Dateien ignorieren statt nen Fehler werfen?

### ISSUE THREAD

**Issue by Natenom** [martin-ueding/geo-activity-playground#31]
Es gibt ab und zu Dateien wie README.md oder andere Dinge neben den Tracks. Das Tool bricht dann immer mit einer Fehlermeldung ab und man muss die Dateien rauswerfen.

Könnte man nicht alles ignorieren, was nicht verwertet werden kann?

Unschön ist das vor allem auch deshalb, weil nach so einem Fehler alle schon eingelesenen Dateien scheinbar nochmal eingelesen werden, weil die Verarbeitung nicht abgeschlossen wurde(?).

```
    raise NotImplementedError(f"Unknown suffix: {path}")
NotImplementedError: Unknown suffix: Activities/alte_touren/lala.kml

**Comment by Natenom** [comment]
Ah, hatte den Issue geschrieben und danach in den Commits seit meinem letzten Pull geschaut und gesehen, dass das jetzt nicht mehr abbricht sondern nur ne Liste der Dateien generiert, die nicht verarbeitet werden konnten.

Schließe hier und danke :)

**Comment by martin-ueding** [comment]
Das Ignorieren von fehlerhaften Dateien kam auch noch von zwei anderen Leuten, einmal per Ticket und einmal per E-Mail. Das scheint wirklich die wichtigste Funktion gewesen zu sein 😊
