### ISSUE TITLE
Some heatmap tiles are empty

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#34]
Sometimes heatmap tiles are completely empty, like this:

![Screenshot_20231126_202908](https://github.com/martin-ueding/geo-activity-playground/assets/976924/1990e752-00b4-473e-b7ef-b4330b7ff8a9)

I have no idea why that is the case. I need to investigate that further.

**Comment by Oi-sin** [comment]
I came here to report the same bug. Mine looks like this:

![image](https://github.com/martin-ueding/geo-activity-playground/assets/32384889/38fab075-1051-4748-970a-aa06db9d61fb)

**Comment by Natenom** [comment]
Habe heute morgen gegen 07 Uhr gepullt und alles neu berechnen lassen und jetzt fehlt nix mehr. :)

**Comment by martin-ueding** [comment]
I have completely changed the way that the heatmap is drawn. And I haven't seen the issue any more. This is the same section as in the first post:

![Screenshot_20231210_072715](https://github.com/martin-ueding/geo-activity-playground/assets/976924/804846a5-202c-4168-ae4b-cbd85902619a)

I would consider this closed. If it comes up again, please reopen this ticket.
