### ISSUE TITLE
Strava API response has no key "request"

### ISSUE THREAD

**Issue by Marcel-Schubert** [martin-ueding/geo-activity-playground#37]
In line 56 in strava_api.py 
            `"expires_at": token_response["request"],`
should be
            `"expires_at": token_response["expires_at"],`
instead.

**Comment by Marcel-Schubert** [comment]
I am a bit puzzled how anyone got the Strava import to work before.

**Comment by martin-ueding** [comment]
Good question! I've fixed that now, will be in the next release. I think that I am the only one who has set this up so far, everyone else used files in a directory. Perhaps I've set it up manually and never triggered that code path.
