### ISSUE TITLE
Improve optics in tile maps with age coloring

### ISSUE THREAD

**Issue by Oi-sin** [martin-ueding/geo-activity-playground#38]
Currently the coloring by age of tiles is hardly visible:
- the colorful background map 'hides' the color of the tiles -> make other map types available, eg any of the gray-scale maps available online
- borderlines are too thick and dominate when zooming out

Examples:
![image](https://github.com/martin-ueding/geo-activity-playground/assets/32384889/938f506e-576c-498d-a682-35ab6059a289)
![image](https://github.com/martin-ueding/geo-activity-playground/assets/32384889/6e503632-76e8-474b-9415-c912c008a576)

**Comment by martin-ueding** [comment]
Yes, a grayscale map would greatly improve the situation. I already have an idea how this can be implemented.

Decreasing the border should be straightforward.

**Comment by martin-ueding** [comment]
I've added a grayscale tile layer there. And now it looks much better! I've also decreased the border weight from 1 to 0.5. Is that better now?

![Screenshot_20231129_213441](https://github.com/martin-ueding/geo-activity-playground/assets/976924/43fd5aa8-6db7-41b1-b3ab-492750639403)

![Screenshot_20231129_213454](https://github.com/martin-ueding/geo-activity-playground/assets/976924/b7a56f96-b9b1-43e3-b4d8-1e24ac1d0500)

**Comment by Oi-sin** [comment]
Definitely looks better, especially when zoomed in.  Thank you!

![image](https://github.com/martin-ueding/geo-activity-playground/assets/32384889/9d8d3ce8-2c91-4e27-acd8-541adde37412)

![image](https://github.com/martin-ueding/geo-activity-playground/assets/32384889/6f399627-8922-4639-add9-e156ff076178)
