### ISSUE TITLE
Interpolation bei großen Lücken in Tracks

### ISSUE THREAD

**Issue by Natenom** [martin-ueding/geo-activity-playground#47]
Habe heute das Verzeichnis `Cache` gelöscht und alles neu auswerten lassen, weil es jetzt die Interpolation gibt.

Dabei ist mir aufgefallen, dass in Tracks, in denen ich z. B. vergessen hatte, auf "Resume" zu drücken und so mehrere Kilometer einer Fahrt fehlen, dass es dann in der "Nähe" Kacheln gibt, die ich angeblich durchfahren hätte. Vor der Interpolation war das nicht so.

Alle diese Kacheln, die mitten in der Pampa ohne Hin- oder Rückweg als "befahren" gelten, stammen von solchen Tracks, wo zwischendrin mehrere Kilometer fehlen.

**Comment by martin-ueding** [comment]
Ich habe die Art verändert, wie die Heatmap gezeichnet wird. Nicht mehr aus den einzelnen Punkten als Punkthäufung. Für Jede Aktivität wird nun eine Linie aus den Punkten interpoliert und gezeichnet. Dadurch hat man nun bei jeder Zoomstufe da eine sinnvolle Anzeige. Das hier ist der gleiche Ausschnitt je nach Stufe:

![Screenshot_20231209_195418](https://github.com/martin-ueding/geo-activity-playground/assets/976924/fde3d84b-d627-4e7e-9de3-e96c358975fa)

![Screenshot_20231209_195430](https://github.com/martin-ueding/geo-activity-playground/assets/976924/ad9684cf-0ac1-4f88-b718-406e2c7d6afe)

![Screenshot_20231209_195438](https://github.com/martin-ueding/geo-activity-playground/assets/976924/2ce3841e-2c97-4282-b442-844c4ce56518)

![Screenshot_20231209_195454](https://github.com/martin-ueding/geo-activity-playground/assets/976924/1857e299-52dd-49b1-9df8-bffc96f6b805)

**Comment by Natenom** [comment]
Hi :)

Das ist zwar auch ein Problem, das ich hatte, aber darum ging es hier im Issue nicht. Es ging um Interpolation, dass plötzlich irgendwo im nirgendwo, wo ich noch nie war, befahrene Kacheln angezeigt werden.

**Comment by martin-ueding** [comment]
Ah, dann habe ich das falsch gelesen. Das Problem mit den Punktewolken in den Heatmaps hattest du dann über Mastodon geschrieben. Ich habe das Ticket hier nochmal aufgemacht, das ist ja in der Tat etwas anderes.

**Comment by martin-ueding** [comment]
Ich habe jetzt einen Fix hierfür auf den `master` gepackt. Du müsstest einmal den Cache löschen, damit die Aktivitäten nochmal neu eingelesen werden.

Es sollten dann keine Kacheln mehr interpoliert werden, wenn der Sprung mehr als eine Kachel weit ist. Wenn der Sprung eher geringer ist, dann wird das aber noch passieren. Da weiß ich nicht, wie relevant das Problem dann noch ist. Ich muss mir noch überlegen, wie ich große Sprünge feststelle. Wahrscheinlich ist alles mit mehr als 30 Sekunden Pause verdächtig. Das will ich auch noch einbauen, wird aber noch ein bisschen länger dauern.

**Comment by martin-ueding** [comment]
Nun habe ich etwas eingebaut, das nach 30 Sekunden Sprung in den Zeitdaten ein neues Segment erstellt. Interpolation findet nur innerhalb von Segmenten statt. Von daher sollte das dann jetzt soweit gelöst sein.
