### ISSUE TITLE
Selective download of unexplored tiles

### ISSUE THREAD

**Issue by Oi-sin** [martin-ueding/geo-activity-playground#53]
As far as I can see, the download links below the map of unexplored tiles supply files that do contain 'all' unexplored tiles. This file can get very large, making it hard to process with other apps. For my squadratinhos it is currently 31MB which cannot be processed by Locus Maps on my mobile device.

It would be a nice feature to be able to download only a selection. This could be the currently visible rectangle in the map or any other method to only select the tiles in the area where I plan my next hike or ride :-)

**Comment by martin-ueding** [comment]
That totally makes sense! I faced a similar problem with OsmAnd.

JavaScript isn't my strong suit, but I managed to hack this together. And now you the download will only export what you have in the viewport.

![Screenshot_20231210_114858](https://github.com/martin-ueding/geo-activity-playground/assets/976924/bf70f363-a4f5-43be-a70f-d76c4156adfb)
