### ISSUE TITLE
Error: `native_field_num` not found

### ISSUE THREAD

**Issue by Natenom** [martin-ueding/geo-activity-playground#57]
There are some files in my repo which cause this error message. Don't know which one because there is no reference to them.

```
2023-12-10 10:07:00 py.warnings WARNING /home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/fitdecode/reader.py:909: UserWarning: 'field "native_field_num" (idx #0) not found in message "field_description"' (local_mesg_num: 0; chunk_offset: 622); adding dummy dev data...
  warnings.warn(msg)
```

**Comment by martin-ueding** [comment]
I've seen that too. It doesn't seem to impact things, though. Interestingly it doesn't appear when one reads the files in text-format. This only came when I changed it to binary reading. But I needed to change that due to the encoding issues that you saw.

**Comment by martin-ueding** [comment]
So apparently that is an upstream issue. There are two upstream issues about this: https://github.com/polyvertex/fitdecode/issues/22 and https://github.com/polyvertex/fitdecode/issues/24. Also there is https://github.com/polyvertex/fitdecode/issues/26 which mentions it.

We can either silence the warning, patch the upstream library or move to a completely different library. The problem with silencing the warning is that we would also silence other warnings and that doesn't seem to be too clever. Patching the upstream library doesn't seem trivial. Moving to a different library might work, but I am also happy to finally be able to import all the problematic files. I am not sure how many bugs a different library might uncover.

So even though it is bad, I'd vote for not fixing this at this time and just hoping that eventually the upstream library gets fixed.
