### ISSUE TITLE
Kein Download mehr von befahrenen Kacheln?

### ISSUE THREAD

**Issue by Natenom** [martin-ueding/geo-activity-playground#63]
Sehe eben erst, dass es wohl keine Möglichkeit mehr gibt, die befahrenen Kacheln herunterzuladen.

Das ist schade, denn ich habe lieber diese Datei benutzt, um neue Strecken von unerledigten Kacheln zu planen, weil man dort besser erkennt, was wirklich noch fehlt.

Das sind z. B. meine erledigten Kacheln und ich möchte in dem oberen Bereich alles abfahren und planen:
![image](https://github.com/martin-ueding/geo-activity-playground/assets/385995/06263f0f-aaa1-458f-a9dd-e16259e47847)

Der Export nur der fehlenden Kacheln sieht so aus:
![image](https://github.com/martin-ueding/geo-activity-playground/assets/385995/8d053c35-b449-4bb2-a60c-2112d7c1b620)

Das Problem: Ich erkenne im unteren Bild nicht, ob die Kacheln in der Mitte schon abgefahren wurden oder nicht. Denn es werden nur unbefahrene Kacheln an der äußeren Grenze eines Gebiets umrandet.

**Comment by martin-ueding** [comment]
Baue ich wieder ein!

**Comment by martin-ueding** [comment]
Wieder drin:

![Screenshot_20231212_071535](https://github.com/martin-ueding/geo-activity-playground/assets/976924/0601d8f4-ee38-4c66-b543-0d961ea8b8cb)
