### ISSUE TITLE
Incorrect values for speed and height for imported *.fit files

### ISSUE THREAD

**Issue by atasingorneq** [martin-ueding/geo-activity-playground#76]
When importing *.fit files, incorrect values are displayed for speed and altitude. The displayed speed is about half as fast as the real speed. The other way is true for altitude, where the displayed values are about twice as high as the real values.

**Comment by martin-ueding** [comment]
For FIT files I just take the speed that is already there and _assume_ that it was in km/h:

```python
                        if "speed" in fields:
                            row["speed"] = fields["speed"]
```

That likely is an issue. I actually don't know what the speed unit is. According to [Garmin's documentation](https://developer.garmin.com/fit/protocol/) it might be mm/s as a unit. But then a sensible bike speed of 20 km/h would be 5.5 m/s of 5500 mm/s. That cannot be the factor 2 that you mean.

Would you mind sending me your file to mu@martin-ueding.de such that I can take a look at it?

**Comment by smartsammler** [comment]
May you, @atasingorneq , test https://github.com/martin-ueding/geo-activity-playground/pull/81 for the speed issue, please? I had similar issues, but found out, that converting from m/s to km/h fixed it. (Wahoo Element Roam 1 with km/h as units). It might also fix your other issue (https://github.com/martin-ueding/geo-activity-playground/issues/77) I got that right.

**Comment by atasingorneq** [comment]
Hello @smartsammler,
now the speed looks right. The altitude information also looks more realistic.

**Comment by folixg** [comment]
I have the same issue with `.fit` files from my Hammerhead Karoo 2. Have not tested the PR but manual calculation indicates that conversion from m/s to km/h is a viable fix.

**Comment by folixg** [comment]
I created a PR (#82) that extracts the used speed units from the fit file.

**Comment by martin-ueding** [comment]
I've included the unit parsing into the `master` code, this will be fixed with the next release.
