### ISSUE TITLE
Wrong decimal separator when importing activities via Strava API

### ISSUE THREAD

**Issue by Oi-sin** [martin-ueding/geo-activity-playground#88]
I imported all of my Strava activites using the Strava API setup into a cleaned cache. Unfortunately, the distance information of the activities is identified wrongly, supposedly due a wrongly used decimal separator in the data. (see issue #86 pointing in a similar direction).

![image](https://github.com/martin-ueding/geo-activity-playground/assets/32384889/ad809df3-55d3-409e-a63c-3b2182c2ec27)

![image](https://github.com/martin-ueding/geo-activity-playground/assets/32384889/e83e679f-7f7f-40f8-9680-8292a8cf3ad6)

**Comment by Oi-sin** [comment]
I just saw another error in the screenshot: the timestamp of the activity is wrong. I suppose Strava stores the time in UTC, while the activity was recorded using CET, i.e. it started at 10:19 am.

**Comment by martin-ueding** [comment]
I screwed around with m and km as units. I think I've fixed some of these issues but haven't published those fixes yet. I'll look into that.

The time zones are another issue. I convert everything to UTC. But I have started to think that this doesn't make so much sense. What we want is local time zone, we don't want to compare absolute times with each other or convert to different time zones. So I think I will change everything to timestamps that are in local time and not time zone aware.

**Comment by martin-ueding** [comment]
Done in 0.19.0.

**Comment by Oi-sin** [comment]
I just updated to the newest github commit and get the following error with Strava API import

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\__main__.py", line 97, in main
    options.func(options)
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\__main__.py", line 71, in <lambda>
    make_activity_repository(options.basedir, options.skip_strava),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\__main__.py", line 114, in make_activity_repository
    import_from_strava_api(repository)
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\importers\strava_api.py", line 96, in import_from_strava_api
    while try_import_strava(repository):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\importers\strava_api.py", line 141, in try_import_strava
    time_series = download_strava_time_series(activity.id, client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\importers\strava_api.py", line 194, in download_strava_time_series
    columns["distance_km"] = streams["distance"].data / 1000
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for /: 'list' and 'int'
```

**Comment by martin-ueding** [comment]
I see, the `streams["distance"].data` is just a mere Python `list[float]`. I've now wrapped it in a Pandas Series, it should work again with the next version.

**Comment by martin-ueding** [comment]
Version 0.20.0 is released you can update and try it out. If the issue persists, please reopen this ticket.
