### ISSUE TITLE
Detect Commutes from Strava Export

### ISSUE THREAD

**Issue by klofrau** [martin-ueding/geo-activity-playground#98]
https://github.com/martin-ueding/geo-activity-playground/blob/11fb381161dee7e9d04af018f2966c262a40ff09/geo_activity_playground/importers/strava_checkout.py#L207

Had to change this line to `is_commute = row["Commute"] == True` in order for the condition to trigger succesfully.
Maybe a change on the strava export format?

**Comment by martin-ueding** [comment]
That's indeed strange. But I've just added a condition that accept either the string `"true"` or the literal boolean value `True`. Will be part of 0.20.0.

**Comment by martin-ueding** [comment]
Version 0.20.0 is released you can update and try it out. If the issue persists, please reopen this ticket.
